# Generated by Django 4.2.10 on 2024-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Прайс')),
                ('bool', models.BooleanField(default=False, verbose_name='Оплачивать')),
            ],
            options={
                'verbose_name_plural': 'Элемент',
            },
        ),
    ]
