# Generated by Django 4.2.10 on 2024-02-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[(1, 'USD'), (2, 'EUR'), (3, 'RUB')], default=1, max_length=2),
        ),
    ]
